name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    strategy:
      matrix:
        include:
        - {
            name: "Mac",
            id: "mac",
            folder: "darwin-x64",
            os: macos-14,
          }
        - {
            name: "Windows",
            id: "win",
            folder: "win32-ia32",
            os: windows-latest,
          }
        - {
            name: "Linux",
            id: "linux",
            folder: "linux-x64",
            os: ubuntu-22.04,
          }
    runs-on: ${{ matrix.os }}
    concurrency: build_${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: build
      id: build
      run: |
        cd app
        npm install
        npm run build-${{ matrix.id }}
        mv app/dist/Calque-${{ matrix.folder }}/* app/dist/
        rmdir app/dist/Calque-${{ matrix.folder }}

    - uses: actions/upload-artifact@v4
      with:
        name: Calque ${{ matrix.name }}
        path: app/dist/Calque-${{ matrix.folder }}
        compression-level: 9

    - name: installer
      id: installer
      if: startsWith(matrix.os, 'windows')
      run: |
        iscc "innosetup.iss"

    - uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'windows')
      with:
        name: Calque ${{ matrix.name }} Installer
        path: "Output/Calque Installer.exe"
        compression-level: 9

    - name: cleanup
      id: cleanup
      run: |
        rm -r app/dist/*